### ISSUE TITLE
Code mismatch

### ISSUE THREAD

**Issue by chrisj42** [shylor/miniventure#13]
I read the other thread about this (#11), but I still have some questions...

You seem to say that this code is the original, or main version, or something, but the site's version (www.playminicraft.com) is the "modded" Minecraft+. But then, why does that website link here for the code? I was wondering that too.
Would it be possible to get the source code for the jar file's version? Or is that one going to remain private?

I ask because I would like to modify it some, namely by adding more options such as world save directory and keyboard controls... however, the entire "local world save" feature does not seem to be present on this version of the code.

**Comment by ChristofferHolmesland** [comment]
This code is commented version of the original. You can still find the original source on Notch's ludum dare page. Minicraft Plus is made by David and Dillyg10 (their names from the old minicraft forum). David can be found under the name Davideesk on minecraftforum.net. Not sure about Dillyg10. Shylor might have some other way of contacting them.

**Comment by chrisj42** [comment]
Ok... so, this David guy is the one who has the "+" code? But, I suppose they linked here because it's the code, just not the "+" code?

**Comment by ChristofferHolmesland** [comment]
Yes David is the one who made the Minicraft+ mod, so he is also the one with the source. This code is for Miniventure, which is trying to make Minicraft easier to mod. So far, this code is just the original Minicraft code with some comments.

**Comment by chrisj42** [comment]
Alright. And so he hasn't chosen to share it, then, right?

**Comment by ChristofferHolmesland** [comment]
Correct.

**Comment by chrisj42** [comment]
Alright. Thanks for all the helpful info!
