### ISSUE TITLE
how do you play do you just click on the file

### ISSUE THREAD

**Issue by hi5universe** [shylor/miniventure#14]
hi

**Comment by ChristofferHolmesland** [comment]
You can play by compiling the source and use the main method from GameApplet.java. Or go to www.playminicraft.com and download the .jar file. To run it you just have to click that file.

**Comment by MidnightStar88** [comment]
hi i am running windows 10 and have the most recent java installed,i have clicked on the download jar file on playminicraft.com but cant seem to open or load the game :( is there anything else i need to do?? im not sure how to use java to open the jar file.... please help im dying to play this game ;) Ashley
![2017-02-17 1](https://cloud.githubusercontent.com/assets/25719040/23053754/86786590-f4d3-11e6-92fe-5d3b9cb41b78.png)
![2017-02-17](https://cloud.githubusercontent.com/assets/25719040/23053765/90c2e872-f4d3-11e6-81fe-1dc38a697a5b.png)

**Comment by gdavid04** [comment]
1) install latest java
2) download the jar file
3) just open it
if didn't works:
make sure, you open it with java and not with explorer, as a zip file
