### ISSUE TITLE
I CAN'T PLAY IT KEEPS ON GOING TO THE FILES

### ISSUE THREAD

**Issue by tacos2172** [shylor/miniventure#15]

**Comment by shylor** [comment]
Is it trying to open as a compressed file? Jar files can do this. Make sure you install Java and set it as the default to open a .jar file and it should work.

**Comment by MidnightStar88** [comment]
hi i am running windows 10 and have the most recent java installed,i have clicked on the download jar file on playminicraft.com but cant seem to open or load the game :( is there anything else i need to do?? im not sure how to use java to open the jar file.... please help im dying to play this game ;) Ashley
![2017-02-17](https://cloud.githubusercontent.com/assets/25719040/23053816/d321a24e-f4d3-11e6-973d-eb5224b3e5b0.png)

**Comment by chrisj42** [comment]
@MidnightStar88
For starters, check that your jar file is indeed where it thinks it is: in your Downloads folder. Try double clicking it in the file explorer and see if it opens from there. But if all else fails, you should just be able to use a command prompt. In case you haven't used one before...

Make sure you're in the folder in explorer that contains your jar file (Downloads, probably). Then, hold shift + right click on the explorer window to bring up the context menu. Select "open command prompt here" or something like that, and then run this command just to double-check java is working: 
java

If it doesn't say "command not found: java" then it should be fine. Run this line to start the jar file:
java -jar "NAMEOFJARFILE.jar"

**Comment by MidnightStar88** [comment]
and do i have to do this everytime i want to play? isnt there a fix for it? so this is exactly what i type in   java -jar "NAMEOFJARFILE.jar"

**Comment by chrisj42** [comment]
@MidnightStar88 
Well, no, that's not EXACTLY what you type; replace NAMEOFJAR with the actual name of the jar file. And you don't need to do the first command; that was one-time, just to double-check that you do, indeed, have a function version of java installed. The last command is necessary, though; it's what actually runs the jar file.

Back to what you said, you _shouldn't_ have to do any of this at all, technically; the computer's supposed to know how to run the file when you click on it. But... based on what you've said, your computer seems to be being difficult, as what happens sometimes, and while I'm sure there would be a way to get it working, this method always works, provided you do it right.

It really ought to work normally, though... in fact, your screenshot suggests you tried to open it from the browser or something. Could you show the message that pops up when you try to open it from Windows Explorer? Also try redownloading it; maybe it was interrupted. The error message suggests that the file wasn't where the computer thought it was, though, so be sure to try and open the file in explorer first.
