### ISSUE TITLE
How to play ONLINE ???

### ISSUE THREAD

**Issue by TheGamingAvalanche** [shylor/miniventure#17]
Hi my name is Gaming Avalanche i need help how you can play ONLINE ??? PLEASE HELP !!!

**Comment by MidnightStar88** [comment]
hi i am running windows 10 and have the most recent java installed,i have clicked on the download jar file on playminicraft.com but cant seem to open or load the game :( is there anything else i need to do?? im not sure how to use java to open the jar file.... please help im dying to play this game ;) Ashley
![2017-02-17](https://cloud.githubusercontent.com/assets/25719040/23053837/fe6e5686-f4d3-11e6-9fad-ad98d74ac2c0.png)

**Comment by MidnightStar88** [comment]
you can play online by going to playminicraft.com and it shud say play minicraft online (flash) just click that....picture below :) hope this helps you 
![2017-02-17](https://cloud.githubusercontent.com/assets/25719040/23053870/37293144-f4d4-11e6-86b1-85a79e2c54f5.png)

**Comment by shylor** [comment]
There is no online/multiplayer on the game.

**Comment by TheGamingAvalanche** [comment]
Thanks DUDE !!! i will play online if it's works !
😁

2017-02-17 12:45 GMT+07:00 Chris Weaver <notifications@github.com>:

**Comment by ConnorTheMiniCrafter** [comment]
how do u playyyyyyyy onliiiiiine

**Comment by ConnorTheMiniCrafter** [comment]
Download Minicraft and try fixing my online multiplayer issue

[Minicrafts.zip](https://github.com/shylor/miniventure/files/2093591/Minicrafts.zip)

**Comment by shylor** [comment]
@ConnorTheMiniCrafter Go to https://playminicraft.com and download the new version. You will need an account on the website to join multiplayer.
